### ISSUE TITLE
config update fails to persist between module reloads

### ISSUE THREAD

**Issue by parasdsingh** [concierge/kpm#13]
Steps to reproduce:

- Do a fresh install of Concierge
- Change `boss`s port with ` /kpm config boss port 80` 
> 'port = 80`
- Check the port's value with `/kpm config boss port`
> 'port = 80`
- Reload the module (as documented in `boss` to put the new value in effect) with `/kpm reload boss`
- Check the port's value with `/kpm config boss port`
> 'port = 8080`

This could be an upstream issue, but opening this here as it's more relevant to `kpm`

**Comment by parasdsingh** [comment]
In-fact all modules and integration fail to attain a persistent config if done via `kpm`

**Comment by drkno** [comment]
This isn't a bug, its because during the migration to a new first-run process we forgot to add the config module to the [defaults table](https://github.com/concierge/Concierge/wiki/Defaults) - something that probably should have been picked up during the review @concierge/core-development . Should be fixed now.

To fix without reinstalling, do a `/kpm install config` and everything will magically start working.
